echo off
rem $Id$
rem 
mkdir .\lib
mkdir .\Debug\bin\dynamic
mkdir .\Debug\bin\static
mkdir .\Debug\dynamiclib
mkdir .\Debug\dynmodules
mkdir .\Debug\sfconvert
mkdir .\Debug\sfconvert_using_DLL
mkdir .\Debug\sfinfo
mkdir .\Debug\sfinfo_using_DLL
mkdir .\Debug\staticlib
mkdir .\Debug\staticmod
mkdir .\Release\bin
mkdir .\Release\bin\dynamic
mkdir .\Release\bin\static
mkdir .\Release\dynamiclib
mkdir .\Release\dynmodules
mkdir .\Release\sfconvert
mkdir .\Release\sfconvert_using_DLL
mkdir .\Release\sfinfo\static
mkdir .\Release\sfinfo_using_DLL
mkdir .\Release\staticlib
mkdir .\Release\staticmod
